- name: Remove default apache2 index.html file
  become: yes
  ignore_errors: yes
  command: rm /var/www/html/index.html 

- name: Upload default index.html for host 
  become: yes
  copy: src=files/index.html dest=/var/www/html/ mode=0644  

- name: Restart webserver
  become: yes
  service: name=httpd state=restarted
